### ISSUE TITLE
AttributeError: python: undefined symbol: Error_GetLastErrorNum

### ISSUE THREAD

**Issue by davidedelvento** [Toblerity/rtree#64] opened 2016-01-15 23:09 UTC
I've installed `spatialindex/1.8.5` from source and I'm trying to compile rtree 0.8.2 against it. Running

```
python setup.py install 
```

tries to import rtree and fails in `ctype` 

```
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import rtree
  File "/glade/scratch/ddvento/build/Rtree-0.8.2/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/glade/scratch/ddvento/build/Rtree-0.8.2/rtree/index.py", line 6, in <module>
    from . import core
  File "/glade/scratch/ddvento/build/Rtree-0.8.2/rtree/core.py", line 110, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: Error_GetLastErrorNum
```

My plan to let rtree know about spatialindex was via the C compiler, but it failed before. How should I proceed?

**Comment by ptallada** [comment] 2016-03-09 10:41
Hi!

The problem is that ctypes.find_library does not at non standard locations, and does not use LD_LIBRARY_PATH.

It is related to #56

**Comment by davidedelvento** [comment] 2016-09-13 19:25
Is there any plan to make a 0.8.3 release which includes this? On the machine where I install software it needs to be released one, not trunk...
Thanks!

**Comment by bekozi** [comment] 2016-10-05 15:43
It would be nice to avoid setting environment variables, so :+1:!

**Comment by hobu** [comment] 2016-10-16 04:07
All activity on this now in #74

**Comment by sgillies** [comment] 2017-08-30 19:29
I'm bringing a discussion with @tomplex in https://github.com/Toblerity/rtree/pull/74#issuecomment-326071336 back here since #74 has stalled.

According to what I read in https://bugs.python.org/issue9998, the issue is fixed in Python 3.6: find_library (which is what rtree uses to find the spatialindex lib) will respect `LD_LIBRARY_PATH` on Linux. Upgrading Python is one possible solution.

Vendorizing a patched ctypes is another solution, but there would need to be backporting and that's a lot of work.

I think the simplest thing that will work for a next release is to try, in https://github.com/Toblerity/rtree/blob/master/rtree/core.py#L124-L127, a `lib_name` that we would like to have found and would have found if we were using the patched ctypes.

**Closed** 2019-11-14 19:45 UTC

**Comment by rahul799** [comment] 2019-12-12 06:53
hey, I am getting this same error with version Rtree-0.9.3. Please help.

**Comment by davidedelvento** [comment] 2019-12-12 12:58
Yes I am getting it too, but I had not reported yet because I was stuck in running additional tests with additional settings. I believe the issue is the one that "solved" https://github.com/Toblerity/rtree/issues/120

**Comment by hobu** [comment] 2019-12-12 13:30
Your libspatialindex is not being found or loaded. Please open a new ticket with details on libspatialindex version, platform, and python version. The test suite now covers 13 different permutations including libspatialindex 1.8.5 and 1.9.3.

**Comment by zaouch** [comment] 2020-01-14 21:14
`sudo apt install libspatialindex-dev python-rtree` solved my issue.

**Comment by dpizetta** [comment] 2020-01-20 12:46
Even using conda environments and its envs, installing "libspatialindex-dev" on the system  it works. I'm using conda envs, but pip to install. 

That's my config:

```
HELPDEV REPORT

* HARDWARE-----------------------------------------------------------------------
    - Machine....................... x86_64
    - Processor..................... Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    - Total Memory.................. 16686 MB
    - Free Memory................... 2853 MB
    - Total Swap.................... 2147 MB
    - Free Swap..................... 2147 MB
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Linux
    - Release....................... 5.0.0-37-generic
    - Platform...................... Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
    - Version....................... #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019
* THREADS------------------------------------------------------------------------
    - Version....................... NPTL 2.27
    - Name.......................... pthread
    - Lock.......................... semaphore
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.7.6
    - C Compiler.................... GCC 7.3.0
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.7.6
* CONDA DISTRIBUTION-------------------------------------------------------------
    - Version....................... 4.8.1
    - Build......................... 3.18.11
* QT BINDINGS--------------------------------------------------------------------
    - PyQt5 Version................. 5.12.3
    - PyQt5 Qt Version.............. 5.12.6
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.9.0
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
* FLOAT--------------------------------------------------------------------------
    - Epsilon....................... 2.220446049250313e-16
    - Digits........................ 15
    - Precision..................... 53
    - Maximum....................... 1.7976931348623157e+308
    - Maximum Exp................... 1024
    - Max. 10 Exp................... 308
    - Minimum....................... 2.2250738585072014e-308
    - Miminim Exp................... -1021
    - Min. 10 Exp................... -307
    - Radix......................... 2
    - Rounds........................ 1
* INTEGER------------------------------------------------------------------------
    - Bits per Digit................ 30
    - Size of Digit................. 4
* PYTHON PACKAGES----------------------------------------------------------------
    - alabaster..................... 0.7.12
    - argh.......................... 0.26.2
    - astroid....................... 2.3.3
    - atomicwrites.................. 1.3.0
    - attrs......................... 19.3.0
    - autopep8...................... 1.4.4
    - Babel......................... 2.8.0
    - backcall...................... 0.1.0
    - bleach........................ 3.1.0
    - certifi....................... 2019.11.28
    - cffi.......................... 1.13.2
    - chardet....................... 3.0.4
    - cloudpickle................... 1.2.2
    - cryptography.................. 2.8
    - decorator..................... 4.4.1
    - defusedxml.................... 0.6.0
    - diff-match-patch.............. 20181111
    - docutils...................... 0.16
    - entrypoints................... 0.3
    - flake8........................ 3.7.9
    - future........................ 0.18.2
    - helpdev....................... 0.6.10
    - idna.......................... 2.8
    - imagesize..................... 1.2.0
    - importlib-metadata............ 1.4.0
    - intervaltree.................. 3.0.2
    - ipykernel..................... 5.1.3
    - ipython....................... 7.11.1
    - ipython-genutils.............. 0.2.0
    - isort......................... 4.3.21
    - jedi.......................... 0.14.1
    - jeepney....................... 0.4.2
    - Jinja2........................ 2.10.3
    - jsonschema.................... 3.2.0
    - jupyter-client................ 5.3.4
    - jupyter-core.................. 4.6.1
    - keyring....................... 21.1.0
    - lazy-object-proxy............. 1.4.3
    - libsass....................... 0.19.4
    - MarkupSafe.................... 1.1.1
    - mccabe........................ 0.6.1
    - mistune....................... 0.8.4
    - more-itertools................ 8.1.0
    - nbconvert..................... 5.6.1
    - nbformat...................... 5.0.3
    - numpydoc...................... 0.9.2
    - packaging..................... 20.0
    - pandocfilters................. 1.4.2
    - parso......................... 0.5.2
    - pathtools..................... 0.1.2
    - pexpect....................... 4.7.0
    - pickleshare................... 0.7.5
    - pip........................... 19.3.1
    - pluggy........................ 0.13.1
    - prompt-toolkit................ 3.0.2
    - psutil........................ 5.6.7
    - ptyprocess.................... 0.6.0
    - pycodestyle................... 2.5.0
    - pycparser..................... 2.19
    - pydocstyle.................... 5.0.2
    - pyflakes...................... 2.1.1
    - Pygments...................... 2.5.2
    - pylama........................ 7.7.1
    - pylint........................ 2.4.4
    - pyparsing..................... 2.4.6
    - PyQt5......................... 5.12.3
    - PyQt5-sip..................... 12.7.0
    - PyQtWebEngine................. 5.12.1
    - pyrsistent.................... 0.15.7
    - python-dateutil............... 2.8.1
    - python-jsonrpc-server......... 0.3.2
    - python-language-server........ 0.31.4
    - pytz.......................... 2019.3
    - pyxdg......................... 0.26
    - PyYAML........................ 5.3
    - pyzmq......................... 18.1.1
    - QDarkStyle.................... 2.8
    - QtAwesome..................... 0.6.1
    - qtconsole..................... 4.6.0
    - QtPy.......................... 1.9.0
    - qtsass........................ 0.1.1
    - requests...................... 2.22.0
    - rope.......................... 0.16.0
    - Rtree......................... 0.9.3
    - SecretStorage................. 3.1.2
    - setuptools.................... 44.0.0.post20200106
    - six........................... 1.14.0
    - snowballstemmer............... 2.0.0
    - sortedcontainers.............. 2.1.0
    - Sphinx........................ 2.3.1
    - sphinxcontrib-applehelp....... 1.0.1
    - sphinxcontrib-devhelp......... 1.0.1
    - sphinxcontrib-htmlhelp........ 1.0.2
    - sphinxcontrib-jsmath.......... 1.0.1
    - sphinxcontrib-qthelp.......... 1.0.2
    - sphinxcontrib-serializinghtml. 1.1.3
    - spyder........................ 4.0.1
    - spyder-kernels................ 1.8.1
    - testpath...................... 0.4.4
    - tornado....................... 6.0.3
    - traitlets..................... 4.3.3
    - typed-ast..................... 1.4.1
    - ujson......................... 1.35
    - urllib3....................... 1.25.7
    - watchdog...................... 0.9.0
    - wcwidth....................... 0.1.8
    - webencodings.................. 0.5.1
    - wheel......................... 0.33.6
    - wrapt......................... 1.11.2
    - wurlitzer..................... 2.0.0
    - yapf.......................... 0.29.0
    - zipp.......................... 1.0.0
```

**Comment by hobu** [comment] 2020-01-20 15:05
You also need the `libspatialindex` conda package installed in your environment.

`conda install -c conda-forge libspatialindex`

**Comment by sgillies** [comment] 2020-01-20 15:33
Don't use pip to install rtree @davidedelvento, use conda so that the rtree package's dependencies are found and installed properly.

**Comment by chrisspen** [comment] 2020-05-23 14:02
> `sudo apt install libspatialindex-dev python-rtree` solved my issue.

Thanks. This fixed it for me as well. However, I only needed `libspatialindex-dev`. With that, the pip version of rtree was able to install, so you don't need the older outdated system package.

**Comment by cocoaaa** [comment] 2020-06-18 19:21
> `sudo apt install libspatialindex-dev python-rtree` solved my issue.

Thanks, I needed to use `python3-rtree` instead.

**Comment by lucgiffon** [comment] 2022-11-23 10:36
`pip install --upgrade rtree` solved the issue encountered while importing geopandas.
