### ISSUE TITLE
Migrate to MIT License?

### ISSUE THREAD

**Issue by yeesian** [Toblerity/rtree#97] opened 2017-12-19 14:24 UTC
> libspatialindex changed from a LGPL to a MIT license as of the 1.8.0 release. For most situations, this should have no impact on the library’s use, but it should open it up for usage in situations that otherwise might have been problematic. Versions of libspatialindex prior to 1.8.0 were licensed LGPL 2.0, with the license description on this file. The codebase has been been updated, with licensing information replaced in headers and source files, to use the MIT license as of the 1.8.0+ release.
> This change was made to support the inclusion of software depending on libspatialindex in static linking-only environments such as embedded systems and Apple’s iOS. libspatialindex versions prior to 1.8.0 will continue to live on as LGPL software, and developers can continue to contribute to them under terms of that license, but the main development effort, and ongoing maintenance, releases, and bug applications, will move forward using the new MIT license at http://github.com/libspatialindex/libspatialindex

[(source)](https://libspatialindex.github.io/#licensing-history)

**Comment by sgillies** [comment] 2017-12-22 19:44
I'm all for it and will check with the other authors in early 2018.

**Comment by adamjmccann** [comment] 2018-06-20 13:56
Any progress on this?

**Comment by Artur-Sampaio** [comment] 2018-08-29 12:59
Any updates?

**Comment by hobu** [comment] 2018-08-29 13:03
Relicensing is messy.

- [ ] Collect a list of all contributors to the source tree and gather their email addresses.
- [ ] Contact all authors, notify them of the proposed licensing change, and request their permission to relicense their contributions as BSD
- [ ] Make a (local, non-public) branch that relicenses the code of those contributors who responded positively to the proposed change.

We are at the first step...

**Comment by Artur-Sampaio** [comment] 2018-08-29 13:19
There are 17 of you listed in https://github.com/Toblerity/rtree/graphs/contributors. Would the @ of all of you do for the first step, and actually @'ing you do for step two?

**Comment by pauloabner** [comment] 2018-08-29 14:00
@hobu
@sgillies
@brentp
@KennethAdamMiller
@dokai
@Juanlu001
@QuLogic
@cgohlke
@kilink
@snorfalorpagus
@ikirker
@jwass
@mwtoews
@vmora
@sebastic
@kannes
@expobrain

**Comment by ikirker** [comment] 2018-08-29 14:14
I only have one tiny commit (which is actually *a deletion* of code rather than an addition, and which I'd entirely forgotten about) so I'm not going to object or anything.

Formally:

_**I grant permission for my contributions to this project to be re-licensed under any license approved by the Open Source Initiative, as listed at <https://opensource.org/licenses/alphabetical>, including but not limited to: BSD 3-clause, BSD 2-clause, MIT, GPL-2 or 3, LGPL-2.1 or 3, AGPL-3.**_

**Comment by hobu** [comment] 2018-08-29 14:18
A 👍 reaction to this statement is hereby deemed sufficient to support the relicensing of Rtree from LGPLv2 to BSD-3 😄 

```
I grant permission for my contributions to this project to be re-licensed 
under any license approved by the Open Source Initiative, as listed at 
https://opensource.org/licenses/alphabetical, including but not 
limited to: BSD 3-clause, BSD 2-clause, MIT, GPL-2 or 3, LGPL-2.1 or 3, AGPL-3.
```

**Comment by hobu** [comment] 2018-08-29 14:39
> Allow me not to grant future relicenses for more restrictive licenses

We're moving to MIT for Rtree, just like libspatialindex. End. Of. Story. That said, us moving to MIT would allow someone to take the code and relicense it to practically whatever they wanted – restrictive AGPLv3, LPGLv3 or whatever. 

By the way, is Rtree being LGPLv2 an actual impediment for anyone? I understand the static linking challenges of LGPLv2 code in static binary environments like iOS. I'm curious if there's something analogous in Python land here.

**Comment by ikirker** [comment] 2018-08-29 14:41
(I was just being non-specific since I'm not bothered what people do with my tiny contribution and am happy to bow out of the discussion at this point. I apologise for causing any hassle/confusion.)

**Comment by hobu** [comment] 2018-08-29 14:44
> I apologise for causing any hassle/confusion.

No need to apologise. Some people get *very* twisted up about these issues. Sometimes they really matter. I don't think they really do so much in this case. What matters is we have a full record here for someone from the future who cares about the issue to investigate.

**Comment by Juanlu001** [comment] 2018-08-29 14:46
> End. Of. Story.

I don't understand the need to use this tone. In any case, I already made my statement and I don't want to fight license wars.

**Comment by hobu** [comment] 2018-08-29 14:47
> End. Of. Story.

Just trying to be definitive 😄 since I already mucked up *which* license we were migrating to once.

**Comment by sebastic** [comment] 2018-08-29 14:51
My contribution was trivial and most likely not copyrightable.

I do give consent for relicensing however.

_**I grant permission for my contributions to this project to be re-licensed under any license approved by the Open Source Initiative, as listed at https://opensource.org/licenses/alphabetical, including but not limited to: BSD 3-clause, BSD 2-clause, MIT, GPL-2 or 3, LGPL-2.1 or 3, AGPL-3.**_

**Comment by kannes** [comment] 2018-08-29 16:40
My sole commit was a minor fix in the documentation https://github.com/Toblerity/rtree/commit/89976ce8f048bcf027187f5f151bec4d124733cf for which I hereby waive all copyright and related rights to the fullest extent allowed by law.

And to be safe I concur with the others:
**_I grant permission for my contributions to this project to be re-licensed under any license approved by the Open Source Initiative, as listed at https://opensource.org/licenses/alphabetical, including but not limited to: BSD 3-clause, BSD 2-clause, MIT, GPL-2 or 3, LGPL-2.1 or 3, AGPL-3._**

**Comment by expobrain** [comment] 2018-08-29 21:08
Fine for me as well

```
I grant permission for my contributions to this project to be re-licensed 
under any license approved by the Open Source Initiative, as listed at 
https://opensource.org/licenses/alphabetical, including but not 
limited to: BSD 3-clause, BSD 2-clause, MIT, GPL-2 or 3, LGPL-2.1 or 3, AGPL-3.
```

**Comment by mwtoews** [comment] 2018-08-29 21:44
I grant permission for my contributions to this project to be re-licensed under the MIT license, reproduced in https://opensource.org/licenses/MIT.

**Comment by vmora** [comment] 2018-08-31 12:33
I do give consent for relicensing under the MIR license.

**Comment by snorfalorpagus** [comment] 2018-08-31 17:36
I grant permission for my contributions to this project to be re-licensed under the MIT license, reproduced in https://opensource.org/licenses/MIT.

**Comment by dokai** [comment] 2018-09-18 14:20
I grant permission for my contributions to this project to be re-licensed under
the MIT license, reproduced in https://opensource.org/licenses/MIT.

**Closed** 2018-12-05 20:51 UTC
